# -*- coding: utf-8 -*-
"""page_rank_cpp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153gNExGT5F6WEBpAAf6yEEDC4LGA2aPx
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pagerank_cpu.cpp
# #include <stdio.h>
# #include <stdlib.h>
# #include <iostream>
# #include <queue>
# #include <cmath>
# #include <ctime>
# #include <vector>
# 
# using namespace std;
# 
# // Function to read graph and apply damping factor
# void get_adj_matrix(float** graph, int n, float d, FILE *inputFilePtr ){
# 
#     if ( inputFilePtr == NULL )  {
#         printf( "input.txt file failed to open." );
#         return ;
#     }
# 
#     int m, indexing;
# 
#     if (fscanf(inputFilePtr, "%d", &m) != 1) {
#         printf("Error reading 'm'\n"); return;
#     }
#     if (fscanf(inputFilePtr, "%d", &indexing) != 1) {
#         printf("Error reading 'indexing'\n"); return;
#     }
# 
#     // Initialize graph with (1-d)/n
#     for(int i = 0; i< n ; i++){
#         graph[i] = (float*)malloc(sizeof(float)* n);
#         for(int j = 0; j< n; ++j){
#             graph[i][j] = (1.0f - d) / (float)n;
#         }
#     }
# 
#     // Add weighted edges
#     while(m--){
#         int source, destin;
#         if (fscanf(inputFilePtr, "%d", &source) != 1) {
#             printf("Error reading 'source'\n"); return;
#         }
#         if (fscanf(inputFilePtr, "%d", &destin) != 1) {
#             printf("Error reading 'destin'\n"); return;
#         }
# 
#         if (indexing == 0){
#             graph[destin][source] += d;
#         }
#         else{
#             graph[destin - 1][source - 1] += d;
#         }
#     }
# }
# 
# // Function to normalize the adjacency matrix (make columns sum to 1)
# void manage_adj_matrix(float** graph, int n){
#     for(int j = 0; j < n; ++j){ // For each column j
#         float sum = 0.0f;
#         for (int i = 0; i< n; ++i){ // Sum up the column
#             sum += graph[i][j];
#         }
# 
#         for (int i = 0; i < n; ++i){ // Normalize the column
#             if (sum != 0.0f){
#                 graph[i][j] /= sum;
#             }
#             else{
#                 // Handle dangling nodes (column sum is 0)
#                 graph[i][j] = 1.0f / (float)n;
#             }
#         }
#     }
# }
# 
# // Function to calculate L1 norm (sum of absolute values)
# float norm(float *vect, int n){
#     float ans = 0.0f;
#     for (int i = 0; i < n; ++i){
#         ans += abs(vect[i]);
#     }
#     return ans;
# }
# 
# // Main power method iteration
# void power_method(float **graph, float *r, int n, int max_iter = 1000, float eps = 1e-6 ){
# 
#     float* r_last = (float*) malloc(n * sizeof(float));
#     float* diff = (float*) malloc(n * sizeof(float)); // More efficient way to calculate norm
# 
#     // Initialize rank vector
#     for(int i = 0; i< n; ++i){
#         r[i] = 1.0f / (float)n;
#     }
# 
#     int iter = 0;
#     for(iter = 0; iter < max_iter; iter++){
#         // r_last = r
#         for(int i = 0; i< n; ++i){
#             r_last[i] = r[i];
#         }
# 
#         // r = graph * r_last (Matrix-Vector Multiplication)
#         for(int i = 0; i< n; ++i){ // For each row i
#             float sum = 0.0f;
#             for (int j = 0; j< n; ++j){ // Dot product of row i with r_last
#                 sum += graph[i][j] * r_last[j];
#             }
#             r[i] = sum;
#         }
# 
#         // diff = r - r_last
#         for(int i = 0; i< n; ++i){
#             diff[i] = r[i] - r_last[i];
#         }
# 
#         // Check for convergence
#         if(norm(diff, n) < eps){
#             printf("Converged after %d iterations (CPU)\n", iter + 1);
#             break;
#         }
#     }
# 
#     if (iter == max_iter) {
#         printf("Reached maximum iterations (%d) (CPU)\n", max_iter);
#     }
# 
#     free(r_last);
#     free(diff);
# }
# 
# // Display top 'count' nodes
# void top_nodes(float *r, int n, int count = 10){
#     priority_queue<pair<float, int>> pq;
# 
#     for(int i = 0; i< n; ++i){
#         pq.push(make_pair(r[i], i+ 1));
#     }
# 
#     int rank = 1;
#     int display_count = (count < n) ? count : n;
# 
#     printf("\nTop %d nodes by PageRank (CPU):\n", display_count);
#     while(rank <= display_count && !pq.empty()){
#         printf("Rank %d: Node %d (Score: %.6f)\n", rank, pq.top().second, pq.top().first);
#         rank++;
#         pq.pop();
#     }
# }
# 
# // Main function
# int main(int argc, char** argv){
# 
#     if (argc < 2) {
#         printf("Usage: %s <input_file>\n", argv[0]);
#         return 1;
#     }
# 
#     clock_t start, end;
#     FILE *inputFilePtr;
# 
#     char * inputfile = argv[1];
#     inputFilePtr = fopen(inputfile, "r");
# 
#     if (inputFilePtr == NULL) {
#         printf("Failed to open file: %s\n", inputfile);
#         return 1;
#     }
# 
#     int n;
#     if (fscanf(inputFilePtr, "%d", &n) != 1) {
#         printf("Error reading 'n' from file.\n");
#         fclose(inputFilePtr);
#         return 1;
#     }
# 
#     printf("Graph size: %d nodes (CPU)\n", n);
# 
#     float d = 0.85f;
#     float** graph = (float**)malloc(n * sizeof(float*));
#     float* r = (float*) malloc(n * sizeof(float));
# 
#     get_adj_matrix(graph, n, d, inputFilePtr);
#     fclose(inputFilePtr); // Close file after reading
# 
#     // Start timer *after* file I/O and setup
#     start = clock();
# 
#     manage_adj_matrix(graph, n);
#     power_method(graph, r, n);
# 
#     // Stop timer *before* printing
#     end = clock();
# 
#     top_nodes(r, n);
# 
#     // Calculate time in milliseconds
#     double time_taken = ((double)(end - start)) / CLOCKS_PER_SEC * 1000.0;
#     printf("\nTime taken: %.2f ms for sequential implementation with %d nodes.\n", time_taken, n);
# 
#     // Free memory
#     for(int i = 0; i < n; i++) {
#         free(graph[i]);
#     }
#     free(graph);
#     free(r);
# 
#     return 0;
# }

# Commented out IPython magic to ensure Python compatibility.
# %%writefile graph_data.txt
# 10
# 15
# 1
# 1 2
# 1 3
# 2 4
# 3 4
# 4 5
# 5 1
# 6 7
# 7 8
# 8 9
# 9 10
# 10 6
# 5 6
# 2 7
# 3 8
# 1 10

!g++ -o pagerank_cpu pagerank_cpu.cpp -O3

!./pagerank_cpu 5000.txt