# -*- coding: utf-8 -*-
"""pagerank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPqCKw4eer955Sg1XBWx8p3wqTH-w0NA
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pagerank_fixed.cu
# #include <stdio.h>
# #include <stdlib.h>
# #include <cuda.h>
# #include <thrust/device_vector.h>
# #include <thrust/reduce.h>
# #include <thrust/sort.h>
# #include <thrust/execution_policy.h>
# #include <time.h>
# #include <cmath>
# 
# // --- CUDA Error Checking Macro ---
# #define HANDLE_ERROR( err ) (HandleError( err, __FILE__, __LINE__ ))
# static void HandleError( cudaError_t err, const char *file, int line ) {
#     if (err != cudaSuccess) {
#         printf( "%s in %s at line %d\n", cudaGetErrorString( err ), file, line );
#         fflush(stdout); // Also flush here
#         exit( EXIT_FAILURE );
#     }
# }
# 
# // Optimized kernel
# __global__ void pagerank_iteration(float* graph, float* r_new, float* r_old,
#                                    float* diff, int n) {
#     int id = blockIdx.x * blockDim.x + threadIdx.x;
#     if (id < n) {
#         float old_val = r_new[id];
#         r_old[id] = old_val;
#         float sum = 0.0f;
#         for (int j = 0; j < n; j++) {
#             sum += r_old[j] * graph[id * n + j];
#         }
#         r_new[id] = sum;
#         diff[id] = fabsf(sum - old_val);
#     }
# }
# 
# // Kernel to normalize adjacency matrix columns
# __global__ void manage_adj_matrix(float* graph, int n) {
#     int col = blockIdx.x * blockDim.x + threadIdx.x;
# 
#     if (col < n) {
#         float sum = 0.0f;
#         for (int row = 0; row < n; row++) {
#             sum += graph[row * n + col];
#         }
# 
#         if (sum != 0.0f) {
#             for (int row = 0; row < n; row++) {
#                 graph[row * n + col] /= sum;
#             }
#         } else {
#             for (int row = 0; row < n; row++) {
#                 graph[row * n + col] = 1.0f / n;
#             }
#         }
#     }
# }
# 
# // Kernel to initialize rank vector
# __global__ void initialize_rank(float* r, int n) {
#     int id = blockIdx.x * blockDim.x + threadIdx.x;
#     if (id < n) {
#         r[id] = 1.0f / n;
#     }
# }
# 
# // Kernel to initialize pair array for sorting
# __global__ void init_pair_array(thrust::pair<float, int>* r_nodes,
#                                 float* r, int n) {
#     int id = blockIdx.x * blockDim.x + threadIdx.x;
#     if (id < n) {
#         r_nodes[id].first = r[id];
#         r_nodes[id].second = id + 1;
#     }
# }
# 
# // Read graph from file
# void get_adj_matrix(float* graph, int n, float d, FILE* inputFilePtr) {
#     int m, indexing;
#     fscanf(inputFilePtr, "%d", &m);
#     fscanf(inputFilePtr, "%d", &indexing);
# 
#     for (int i = 0; i < n * n; ++i) {
#         graph[i] = (1.0f - d) / n;
#     }
# 
#     while (m--) {
#         int source, destin;
#         fscanf(inputFilePtr, "%d", &source);
#         fscanf(inputFilePtr, "%d", &destin);
# 
#         if (indexing == 0) {
#             graph[destin * n + source] += d;
#         } else {
#             graph[(destin - 1) * n + (source - 1)] += d;
#         }
#     }
# }
# 
# 
# // Optimized power method
# void power_method(float* gpu_graph, float* r, int n, int nblocks, int blocksize,
#                  int max_iter = 1000, float eps = 1e-6) {
#     float *gpu_r, *gpu_r_old, *gpu_diff;
#     HANDLE_ERROR( cudaMalloc(&gpu_r, n * sizeof(float)) );
#     HANDLE_ERROR( cudaMalloc(&gpu_r_old, n * sizeof(float)) );
#     HANDLE_ERROR( cudaMalloc(&gpu_diff, n * sizeof(float)) );
# 
#     initialize_rank<<<nblocks, blocksize>>>(gpu_r, n);
#     HANDLE_ERROR( cudaPeekAtLastError() );
#     HANDLE_ERROR( cudaDeviceSynchronize() );
# 
#     int iter;
#     for (iter = 0; iter < max_iter; iter++) {
#         pagerank_iteration<<<nblocks, blocksize>>>(gpu_graph, gpu_r, gpu_r_old, gpu_diff, n);
#         HANDLE_ERROR( cudaPeekAtLastError() );
#         HANDLE_ERROR( cudaDeviceSynchronize() );
# 
#         float diff_sum = thrust::reduce(thrust::device, gpu_diff, gpu_diff + n);
# 
#         if (diff_sum < eps) {
#             printf("Converged after %d iterations\n", iter + 1); fflush(stdout);
#             break;
#         }
#     }
# 
#     if (iter == max_iter) {
#         printf("Reached maximum iterations (%d)\n", max_iter); fflush(stdout);
#     }
# 
#     // Copy final ranks back to host
#     HANDLE_ERROR( cudaMemcpy(r, gpu_r, n * sizeof(float), cudaMemcpyDeviceToHost) );
# 
#     HANDLE_ERROR( cudaFree(gpu_r) );
#     HANDLE_ERROR( cudaFree(gpu_r_old) );
#     HANDLE_ERROR( cudaFree(gpu_diff) );
# }
# 
# // Display top nodes
# void top_nodes(float* r, int n, int nblocks, int blocksize, int count = 10) {
#     thrust::pair<float, int>* r_nodes = (thrust::pair<float, int>*)malloc(n * sizeof(thrust::pair<float, int>));
#     thrust::pair<float, int>* gpu_r_nodes;
#     HANDLE_ERROR( cudaMalloc(&gpu_r_nodes, n * sizeof(thrust::pair<float, int>)) );
# 
#     float* gpu_r;
#     HANDLE_ERROR( cudaMalloc(&gpu_r, n * sizeof(float)) );
#     HANDLE_ERROR( cudaMemcpy(gpu_r, r, n * sizeof(float), cudaMemcpyHostToDevice) );
# 
#     init_pair_array<<<nblocks, blocksize>>>(gpu_r_nodes, gpu_r, n);
#     HANDLE_ERROR( cudaPeekAtLastError() );
#     HANDLE_ERROR( cudaDeviceSynchronize() );
# 
#     HANDLE_ERROR( cudaMemcpy(r_nodes, gpu_r_nodes, n * sizeof(thrust::pair<float, int>), cudaMemcpyDeviceToHost) );
# 
#     // Sort on the host
#     thrust::sort(thrust::host, r_nodes, r_nodes + n);
# 
#     printf("\nTop %d nodes by PageRank:\n", count); fflush(stdout);
#     for (int rank = 1; rank <= count && rank <= n; rank++) {
#         printf("Rank %d: Node %d (Score: %.6f)\n",
#                rank, r_nodes[n - rank].second, r_nodes[n - rank].first);
#         fflush(stdout);
#     }
# 
#     free(r_nodes);
#     HANDLE_ERROR( cudaFree(gpu_r_nodes) );
#     HANDLE_ERROR( cudaFree(gpu_r) );
# }
# 
# // Main function
# int main(int argc, char** argv) {
#     if (argc < 3) {
#         printf("Usage: %s <input_file> <block_size>\n", argv[0]); fflush(stdout);
#         return 1;
#     }
# 
#     char* inputfile = argv[1];
#     int blocksize = atoi(argv[2]);
# 
#     FILE* inputFilePtr = fopen(inputfile, "r");
#     if (!inputFilePtr) {
#         printf("Failed to open input file: %s\n", inputfile); fflush(stdout);
#         return 1;
#     }
# 
#     int n;
#     fscanf(inputFilePtr, "%d", &n);
#     int nblocks = (n + blocksize - 1) / blocksize;
# 
#     printf("Graph size: %d nodes\n", n); fflush(stdout);
#     printf("Block size: %d threads\n", blocksize); fflush(stdout);
#     printf("Grid size: %d blocks\n", nblocks); fflush(stdout);
# 
#     float* graph = (float*)malloc(n * n * sizeof(float));
#     float* r = (float*)malloc(n * sizeof(float));
# 
#     get_adj_matrix(graph, n, 0.85f, inputFilePtr);
#     fclose(inputFilePtr);
# 
#     float* gpu_graph;
#     HANDLE_ERROR( cudaMalloc(&gpu_graph, n * n * sizeof(float)) );
#     HANDLE_ERROR( cudaMemcpy(gpu_graph, graph, n * n * sizeof(float), cudaMemcpyHostToDevice) );
# 
#     clock_t start = clock();
# 
#     manage_adj_matrix<<<nblocks, blocksize>>>(gpu_graph, n);
#     HANDLE_ERROR( cudaPeekAtLastError() );
#     HANDLE_ERROR( cudaDeviceSynchronize() );
# 
#     power_method(gpu_graph, r, n, nblocks, blocksize);
# 
#     // Pass the host 'r' array, which now contains the final ranks
#     top_nodes(r, n, nblocks, blocksize);
# 
#     clock_t end = clock();
# 
#     double time_taken = ((double)(end - start)) / CLOCKS_PER_SEC * 1000.0;
#     printf("\nTime taken: %.2f ms for parallel implementation with %d nodes\n", time_taken, n);
#     fflush(stdout);
# 
#     free(graph);
#     free(r);
#     HANDLE_ERROR( cudaFree(gpu_graph) );
# 
#     return 0;
# }

# Commented out IPython magic to ensure Python compatibility.
# %%writefile graph_data.txt
# 10
# 15
# 1
# 1 2
# 1 3
# 2 4
# 3 4
# 4 5
# 5 1
# 6 7
# 7 8
# 8 9
# 9 10
# 10 6
# 5 6
# 2 7
# 3 8
# 1 10

!nvcc -o pagerank_fixed pagerank_fixed.cu -O3 -arch=sm_75 && echo "Compilation successful!"

!./pagerank_fixed 5000.txt 256